# Generated by Django 5.2.13 on 2026-04-16 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0004_bank_alter_bankaccount_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('import_type', models.CharField(max_length=100, verbose_name='Тип импорта')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('completed', 'Завершён'), ('failed', 'Завершён с ошибкой')], default='new', max_length=20, verbose_name='Статус')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='org.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Пакет импорта',
                'verbose_name_plural': 'Пакеты импорта',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('file', models.FileField(upload_to='imports/', verbose_name='Файл')),
                ('original_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME type')),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Размер в байтах')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('parsed', 'Разобран'), ('failed', 'Ошибка')], default='new', max_length=20, verbose_name='Статус')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='imports.importbatch', verbose_name='Пакет импорта')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='import_files', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Файл импорта',
                'verbose_name_plural': 'Файлы импорта',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ImportRowRaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('row_number', models.PositiveIntegerField(verbose_name='Номер строки')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processed', 'Обработана'), ('failed', 'Ошибка')], default='new', max_length=20, verbose_name='Статус')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows_raw', to='imports.importbatch', verbose_name='Пакет импорта')),
                ('import_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows_raw', to='imports.importfile', verbose_name='Файл импорта')),
            ],
            options={
                'verbose_name': 'Сырая строка импорта',
                'verbose_name_plural': 'Сырые строки импорта',
                'ordering': ('import_file', 'row_number'),
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='Код ошибки')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('level', models.CharField(choices=[('error', 'Ошибка'), ('warning', 'Предупреждение')], default='error', max_length=20, verbose_name='Уровень')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importbatch', verbose_name='Пакет импорта')),
                ('import_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importfile', verbose_name='Файл импорта')),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importrowraw', verbose_name='Сырая строка')),
            ],
            options={
                'verbose_name': 'Ошибка импорта',
                'verbose_name_plural': 'Ошибки импорта',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='importrowraw',
            constraint=models.UniqueConstraint(fields=('import_file', 'row_number'), name='unique_import_row_number_per_file'),
        ),
    ]
