# Generated by Django 5.2.13 on 2026-04-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_attachment_auditlog_comment'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Выплачено')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='core.currency', verbose_name='Валюта')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='people.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Начисление зарплаты',
                'verbose_name_plural': 'Начисления зарплаты',
                'ordering': ('-period_start',),
            },
        ),
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ставка')),
                ('effective_from', models.DateField(verbose_name='Действует с')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_rates', to='core.currency', verbose_name='Валюта')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_rates', to='people.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Ставка сотрудника',
                'verbose_name_plural': 'Ставки сотрудников',
                'ordering': ('-effective_from',),
            },
        ),
    ]
