# Generated by Django 5.2.13 on 2026-04-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment_auditlog_comment'),
        ('org', '0004_bank_alter_bankaccount_options_and_more'),
        ('payroll', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('payment_date', models.DateField(verbose_name='Дата выплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('paid', 'Выплачен'), ('failed', 'Ошибка')], default='planned', max_length=20, verbose_name='Статус')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_payments', to='core.currency', verbose_name='Валюта')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='people.employee', verbose_name='Сотрудник')),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payroll.payroll', verbose_name='Начисление')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплаты',
                'ordering': ('-payment_date', '-id'),
            },
        ),
    ]
