# Generated by Django 5.2.2 on 2026-04-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrollpayment',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salaryrate',
            name='employee',
        ),
    ]
