# Generated by Django 5.2.2 on 2026-04-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payroll_employee_and_more'),
        ('people', '0002_remove_employee_company_remove_employee_user_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='engagement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='people.personcompanyengagement', verbose_name='Занятость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payrollpayment',
            name='engagement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_payments', to='people.personcompanyengagement', verbose_name='Занятость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaryrate',
            name='engagement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salary_rates', to='people.personcompanyengagement', verbose_name='Занятость'),
            preserve_default=False,
        ),
    ]
