# Generated by Django 5.2.13 on 2026-04-15 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_client_project_bankaccount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('employment_type', models.CharField(choices=[('employee', 'Сотрудник'), ('contractor', 'Подрядчик'), ('founder', 'Учредитель')], default='employee', max_length=20, verbose_name='Тип')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата найма')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='org.company', verbose_name='Компания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ('full_name',),
            },
        ),
    ]
