# Generated by Django 5.2.2 on 2026-04-21 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_alter_company_code'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Отображаемое имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('external_id', models.CharField(blank=True, default='', help_text='Идентификатор из внешней системы (например, Access)', max_length=100, verbose_name='Внешний ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='PersonCompanyEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('engagement_type', models.CharField(choices=[('employee', 'Сотрудник'), ('contractor', 'Подрядчик'), ('founder', 'Учредитель')], default='employee', max_length=20, verbose_name='Тип')),
                ('job_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Должность')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('external_id', models.CharField(blank=True, default='', help_text='Идентификатор из внешней системы (например, Access)', max_length=100, verbose_name='Внешний ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_engagements', to='org.company', verbose_name='Компания')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='people.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Занятость',
                'verbose_name_plural': 'Занятости',
                'ordering': ('person__last_name', 'person__first_name', 'company__short_name'),
            },
        ),
    ]
