# Generated by Django 5.2.2 on 2026-04-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_engagement_payrollpayment_engagement_and_more'),
        ('people', '0002_remove_employee_company_remove_employee_user_person_and_more'),
        ('worklog', '0004_remove_timesheetentry_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='uniq_person_external_id'),
        ),
        migrations.AddConstraint(
            model_name='personcompanyengagement',
            constraint=models.UniqueConstraint(fields=('person', 'company', 'engagement_type'), name='uniq_engagement_person_company_type'),
        ),
        migrations.AddConstraint(
            model_name='personcompanyengagement',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='uniq_engagement_external_id'),
        ),
    ]
