# Generated by Django 5.2.13 on 2026-04-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_attachment_auditlog_comment'),
        ('org', '0004_bank_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('transaction_date', models.DateField(verbose_name='Дата операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('direction', models.CharField(choices=[('inflow', 'Поступление'), ('outflow', 'Списание')], max_length=20, verbose_name='Направление')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('external_id', models.CharField(blank=True, max_length=255, verbose_name='Внешний ID')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='org.bankaccount', verbose_name='Банковский счёт')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Банковская операция',
                'verbose_name_plural': 'Банковские операции',
                'ordering': ('-transaction_date', '-id'),
            },
        ),
    ]
