# Generated by Django 5.2.2 on 2026-04-21 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        ('core', '0002_attachment_auditlog_comment'),
        ('org', '0008_alter_company_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='amount_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Сумма в RUB'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='core.exchangerate', verbose_name='Применённый курс'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('company', 'external_id'), name='unique_bank_transaction_external_id_per_company'),
        ),
    ]
