# Generated by Django 5.2.2 on 2026-04-16 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0003_alter_businessdirection_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('report_type', models.CharField(choices=[('cashflow', 'Cash Flow'), ('pnl', 'P&L'), ('unit_economics', 'Unit Economics')], max_length=30, verbose_name='Тип отчёта')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные отчёта')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Сгенерировано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='org.company', verbose_name='Компания')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='org.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Снимок отчёта',
                'verbose_name_plural': 'Снимки отчётов',
                'ordering': ('-period_start', '-generated_at'),
            },
        ),
    ]
