# Generated by Django 5.2.13 on 2026-04-16 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('core', '0002_attachment_auditlog_comment'),
        ('expenses', '0001_initial'),
        ('org', '0004_bank_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('target_type', models.CharField(choices=[('bank_transaction', 'Банковская операция'), ('timesheet_entry', 'Запись таймшита'), ('payroll', 'Начисление зарплаты'), ('payroll_payment', 'Выплата зарплаты'), ('revenue', 'Выручка'), ('invoice', 'Счёт'), ('act', 'Акт'), ('expense', 'Расход'), ('allocation', 'Разнесение'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Тип объекта')),
                ('target_id', models.PositiveBigIntegerField(verbose_name='ID объекта')),
                ('adjustment_date', models.DateField(verbose_name='Дата корректировки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Корректировка',
                'verbose_name_plural': 'Корректировки',
                'ordering': ('-adjustment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('source_type', models.CharField(choices=[('bank_transaction', 'Банковская операция'), ('timesheet_entry', 'Запись таймшита'), ('payroll', 'Начисление зарплаты'), ('payroll_payment', 'Выплата зарплаты'), ('revenue', 'Выручка'), ('invoice', 'Счёт'), ('act', 'Акт'), ('expense', 'Расход'), ('allocation', 'Разнесение'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Тип источника')),
                ('source_id', models.PositiveBigIntegerField(verbose_name='ID источника')),
                ('allocation_date', models.DateField(verbose_name='Дата разнесения')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('business_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='org.businessdirection', verbose_name='Направление бизнеса')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='core.currency', verbose_name='Валюта')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='expenses.expensecategory', verbose_name='Категория расхода')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='org.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Разнесение',
                'verbose_name_plural': 'Разнесения',
                'ordering': ('-allocation_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('left_source_type', models.CharField(choices=[('bank_transaction', 'Банковская операция'), ('timesheet_entry', 'Запись таймшита'), ('payroll', 'Начисление зарплаты'), ('payroll_payment', 'Выплата зарплаты'), ('revenue', 'Выручка'), ('invoice', 'Счёт'), ('act', 'Акт'), ('expense', 'Расход'), ('allocation', 'Разнесение'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Левый источник')),
                ('left_source_id', models.PositiveBigIntegerField(verbose_name='ID левого источника')),
                ('right_source_type', models.CharField(choices=[('bank_transaction', 'Банковская операция'), ('timesheet_entry', 'Запись таймшита'), ('payroll', 'Начисление зарплаты'), ('payroll_payment', 'Выплата зарплаты'), ('revenue', 'Выручка'), ('invoice', 'Счёт'), ('act', 'Акт'), ('expense', 'Расход'), ('allocation', 'Разнесение'), ('adjustment', 'Корректировка')], max_length=30, verbose_name='Правый источник')),
                ('right_source_id', models.PositiveBigIntegerField(verbose_name='ID правого источника')),
                ('status', models.CharField(choices=[('pending', 'Не сверено'), ('matched', 'Сверено'), ('mismatch', 'Есть расхождение')], default='pending', max_length=20, verbose_name='Статус')),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Разница')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_records', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_records', to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Запись сверки',
                'verbose_name_plural': 'Записи сверки',
                'ordering': ('-created_at',),
            },
        ),
    ]
