# Generated by Django 5.2.13 on 2026-04-15 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0002_client_project_bankaccount_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worklog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('work_date', models.DateField(verbose_name='Дата')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Часы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Биллабельно')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='people.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='org.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Таймшит',
                'verbose_name_plural': 'Таймшиты',
                'ordering': ('-work_date',),
                'constraints': [models.UniqueConstraint(fields=('employee', 'project', 'work_date'), name='unique_worklog_per_day')],
            },
        ),
    ]
