# Generated by Django 5.2.13 on 2026-04-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worklog',
        ),
    ]
