# Generated by Django 5.2.13 on 2026-04-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0004_bank_alter_bankaccount_options_and_more'),
        ('people', '0001_initial'),
        ('worklog', '0002_delete_worklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('work_date', models.DateField(verbose_name='Дата работы')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Часы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_billable', models.BooleanField(default=True, verbose_name='Биллабельно')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='org.company', verbose_name='Компания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='people.employee', verbose_name='Сотрудник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timesheet_entries', to='org.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Запись таймшита',
                'verbose_name_plural': 'Записи таймшита',
                'ordering': ('-work_date', '-id'),
            },
        ),
    ]
