# Generated by Django 5.2.2 on 2026-04-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_employee_company_remove_employee_user_person_and_more'),
        ('worklog', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='employee',
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='engagement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_entries', to='people.personcompanyengagement', verbose_name='Занятость'),
            preserve_default=False,
        ),
    ]
