# Generated by Django 5.2.13 on 2026-04-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_attachment_auditlog_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('company_type', models.CharField(choices=[('legal_entity', 'Юрлицо'), ('individual', 'Физлицо/ИП')], default='legal_entity', max_length=30, verbose_name='Тип компании')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='УНП/ИНН/БИН')),
                ('registration_country', models.CharField(max_length=2, verbose_name='Страна регистрации')),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='core.currency', verbose_name='Базовая валюта')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BusinessDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_directions', to='org.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Направление бизнеса',
                'verbose_name_plural': 'Направления бизнеса',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_business_direction_name_per_company')],
            },
        ),
    ]
