# Generated by Django 5.2.13 on 2026-04-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment_auditlog_comment'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='УНП/ИНН/БИН')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='org.company', verbose_name='Компания-владелец')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата старта')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('business_direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='org.businessdirection', verbose_name='Направление бизнеса')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='org.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='org.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Банк')),
                ('account_number', models.CharField(max_length=100, verbose_name='Номер счёта')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной счёт')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Банковский счёт',
                'verbose_name_plural': 'Банковские счета',
                'ordering': ('company__name', 'bank_name', 'account_number'),
                'constraints': [models.UniqueConstraint(fields=('company', 'account_number'), name='unique_account_number_per_company')],
            },
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_client_name_per_company'),
        ),
    ]
