# Generated by Django 5.2.13 on 2026-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_client_project_bankaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdirection',
            name='code',
            field=models.CharField(blank=True, help_text='Если оставить пустым, код будет сгенерирован автоматически.', max_length=50, unique=True, verbose_name='Код'),
        ),
    ]
