# Generated by Django 5.2.2 on 2026-04-16 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_alter_businessdirection_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('code', models.CharField(blank=True, help_text='Если оставить пустым, код будет сгенерирован автоматически.', max_length=50, unique=True, verbose_name='Код')),
                ('country', models.CharField(blank=True, help_text='2 символа - RU/KZ/BY', max_length=2, verbose_name='Код Страны')),
                ('bic', models.CharField(blank=True, max_length=50, verbose_name='БИК / SWIFT')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('company__name', 'bank', 'account_number'), 'verbose_name': 'Банковский счёт', 'verbose_name_plural': 'Банковские счета'},
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, help_text='Если оставить пустым, код будет сгенерирован автоматически.', max_length=50, unique=True, verbose_name='Код'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='org.bank', verbose_name='Банк'),
        ),
    ]
