# Generated by Django 5.2.2 on 2026-04-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_bank_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, help_text='Если оставить пустым, код будет сгенерирован автоматически.', max_length=20, null=True, verbose_name='Код'),
        ),
    ]
