# Generated by Django 5.2.2 on 2026-04-20 12:23

from django.db import migrations


# Маппинг id → правильный код.
# Используем id, потому что на этом этапе у нас три известные компании
# с id=1, 2, 3 — это явная коррекция стартовых данных.
COMPANY_CODES = {
    1: "DREAM_BY",
    2: "DREAM_KZ",
    3: "PRIDE_RU",
}


def set_initial_company_codes(apps, schema_editor):
    """
    Перезаписывает автосгенерированные коды трёх стартовых компаний
    на осмысленные: DREAM_BY, DREAM_KZ, PRIDE_RU.
    """
    Company = apps.get_model('org', 'Company')

    for company_id, code in COMPANY_CODES.items():
        Company.objects.filter(pk=company_id).update(code=code)


def reverse_set_initial_company_codes(apps, schema_editor):
    """
    Обратная операция — вернуть коды обратно к пустым значениям.
    После отката можно прогнать миграцию 0006 повторно для авто-генерации.
    """
    Company = apps.get_model('org', 'Company')
    Company.objects.filter(pk__in=COMPANY_CODES.keys()).update(code=None)


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_populate_company_codes'),
    ]

    operations = [
        migrations.RunPython(
            set_initial_company_codes,
            reverse_code=reverse_set_initial_company_codes,
        ),
    ]
