# Generated by Django 5.2.2 on 2026-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_set_initial_company_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, help_text='Если оставить пустым, код будет сгенерирован автоматически.', max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
