# Generated by Django 5.2.2 on 2026-04-16 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_attachment_auditlog_comment'),
        ('org', '0003_alter_businessdirection_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма выручки')),
                ('recognized_date', models.DateField(blank=True, null=True, verbose_name='Дата признания выручки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='org.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='core.currency', verbose_name='Валюта')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenues', to='org.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Выручка',
                'verbose_name_plural': 'Выручка',
                'ordering': ('-period_start', '-id'),
            },
        ),
    ]
