# Generated by Django 5.2.13 on 2026-04-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attachment_auditlog_comment'),
        ('org', '0004_bank_alter_bankaccount_options_and_more'),
        ('revenue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('act_date', models.DateField(verbose_name='Дата акта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма документа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='org.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='core.currency', verbose_name='Валюта')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='org.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Акт',
                'verbose_name_plural': 'Акты',
                'ordering': ('-act_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ActLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='Номер строки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='revenue.act', verbose_name='Акт')),
            ],
            options={
                'verbose_name': 'Строка акта',
                'verbose_name_plural': 'Строки акта',
                'ordering': ('act', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('issue_date', models.DateField(verbose_name='Дата счёта')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок оплаты')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('issued', 'Выставлен'), ('paid', 'Оплачен')], default='draft', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма документа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='org.client', verbose_name='Клиент')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='org.company', verbose_name='Компания')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.currency', verbose_name='Валюта')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='org.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ('-issue_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('line_number', models.PositiveIntegerField(default=1, verbose_name='Номер строки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Цена')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='revenue.invoice', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Строка счёта',
                'verbose_name_plural': 'Строки счёта',
                'ordering': ('invoice', 'line_number', 'id'),
            },
        ),
    ]
